### ISSUE TITLE
Auto Target for Minions

### ISSUE THREAD

**Issue by Xatan** [ebonyfaye/ema#26]
heya Blossom, I am wondering how Assist should work.
At present, if i press Assist key on each minion character then each minion *does* target the target of the Main character, but this only lasts for one target, and pressing Assist repeatedly is too time consuming and unwieldy.
When the target dies the minion characters do *not* auto-select the next target of the Main character.
It is annoying to have to press Assist again on each minion character.
Could you please provide an Auto-Target key binding,, a  Cancel Auto-Target key binding and a Minions Auto Target key binding?
Auto-Target would allow a Minion to receive an addon-to-addon command from the Main character, to automatically change the target of the minion character to be the target of the Main character whenever the Main's target changes. 
I imagine that you would implement this in the same way that pressing the Follow Me key on the Main will send addon commands to all the other minion characters and execute a macro on each minion. 
The Auto Target command would be broadcast automatically from the Main character when the Main changes target. 
When the Master char presses a keybind for Minions Auto Target then all the minions would receive a command to set all the minions in Auto-Target  mode, without having to go onto each minion and press Auto-Target individually.
My apologies if i have misunderstood how Assist is meant to work but Assist only works for me for one target and I have to press Assist again repeatedly on minions at the moment.
Thanks in advance :)

**Comment by DejayRezme** [comment]
Addons may not change the target of the player. They can't even set the focus, this was banned because of healbot I think.

The way I have set it up (and I think the best way?) is to set the focus of each box to the master. EMA has a /click EMAFocusMaster. You need to do this every time you log on for each toon.

Now you set all your spell macros like:
/cast [@focustarget] Moonfire 
and they will always target what you target on your main. Downside is that you can't attack without having your focus target set. 

PS: See issue#24 https://github.com/ebonyfaye/ema/issues/24

**Comment by ebonyfaye** [comment]
No true ema can change the target/focus/assist but olny out of combat no
reload just need to be out off combat.

**Comment by DejayRezme** [comment]
Oh so you could make an option that the whole team automatically focuses the leader on startup? That would be a cool feature :)

EDIT: Ok I just seen on dual-boxing that you can actually put the "/click EMAFocusMaster" into your dps or heal macros. So this can be done automatically. But I still think adding it to startup would be nicer since then you don't need to add this to your macro(s).

**Comment by ebonyfaye** [comment]
No you can not call focus without a hardware event so this can not be done u need a button press.
