### ISSUE TITLE
Sell Already Known Toy

### ISSUE THREAD

**Issue by nancikennedy** [ebonyfaye/ema#42]
Not your fault, but this setting is now annoying to use with the change to the API for deleting items. Could you remove or separate the delete functionality from this setting? Thanks :)

2x [ADDON_ACTION_BLOCKED] AddOn 'EMA' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: ?
[string "=[C]"]: in function `DeleteCursorItem'
[string "@EMA\Modules\Sell.lua"]:1122: in function `?'
[string "@Ace3\AceTimer-3.0\AceTimer-3.0-17.lua"]:55: in function <Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>

**Comment by DejayRezme** [comment]
Maybe this could be changed so you have a popup window on each follower so you have to click "click to delete ToyX ?". 
You'd have to click on each screen but this would still be an improvement compared to having to do search for it in the bag of each toon and manually destroying it.

PS: Apparently you can even delete multiple items with a single hardware event but I'm unsure how that would work. I guess you have a button with an "onClick" event handler that loops through multiple items, picks them up and destroys them and that would because it's code execute inside an hardware event.

**Comment by ebonyfaye** [comment]
this was removed if the can not be sold for a price
